import ResponsiveAppBar from "@/Components/Home/Utility/ResponsiveAppBar";
import { UseStoreContextProvider } from "@/Context/UseStoreContext";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ORG Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
        />
      </head>
      <body className={inter.className}>
        <UseStoreContextProvider>
          <ResponsiveAppBar children={children} />
        </UseStoreContextProvider>{" "}
      </body>
    </html>
  );
}
